# -*- coding: utf8 -*-
channels = {
    '1HD': '1hd',
    '24Doc': '24_doc',
    '2x2': '2x2',
    '360° ПОДМОСКОВЬЕ HD': '360dhd',
    '365 дней ТВ': '365_day',
    '5 канал': 'piter5_rus',
    '8 Канал': '8_kanal',
    'A-One Hip Hop': 'a-onhiphop',
    'A-ONE': 'a-one',
    'AB Moteurs': 'abmotors',
    'Amazing Life': 'amazing',
    'AMC': 'ntv+41',
    'Amedia 2': 'amedia',
    'Amedia Hit': 'amediahit',
    'Amedia Premium HD': 'amediaprhd',
    'Amedia1': 'amedia1',
    'Angel TV': 'angeltv',
    'Ani': 'ani',
    'Animal Family HD': 'anfamilhd',
    'Animal Planet HD': 'animalplhd',
    'Animal Planet': 'ntv+17',
    'Arirang': 'arirang',
    'Arte HD': 'artehd',
    'Baby TV': 'baby_tv',
    'BBC Entertainment': 'bbc_entert',
    'BBC World': 'bbc-world',
    'BBC': 'ntv+25',
    'BizTV': 'biztv',
    'Bloomberg': 'ntv+33',
    'Blue Hustler': 'bluehust',
    'Bollywood HD': 'bollywood',
    'Boomerang': 'boomerang',
    'Brazzers TV Europe': 'brazzeuro',
    'Bridge TV': 'bridge-tv',
    'C Music TV': 'c_music_tv',
    'Candy 3D HD': 'candy3d',
    'Candy TV': 'candy',
    'Cartoon Network': 'ntv+29',
    'CBS Reality': 'reality',
    'CBS_Drama': 'drama',
    'CCTV News': 'cctvnews',
    'CCTV': 'cctv',
    'CNBC': 'cnbc',
    'CNN (eng)': 'cnn_eng',
    'CNN': 'ntv+30',
    'Da Vinci': 'da vinci',
    'Dange TV': 'dangetv',
    'Daring!TV': 'daring!tv',
    'Deutsche Welle (DEU)': 'dw_deu',
    'Deutsche Welle': 'dw',
    'Discovery Channel': 'ntv+16',
    'Discovery HD Showcase': 'hdshowcase',
    'Discovery Science': 'ntv+28',
    'Discovery Восточная Европа': 'discov_ve',
    'DTX': 'dtxemea',
    'DuckTV': 'ducktv',
    'English Club TV': 'englishclu',
    'Eureka HD': 'eurekahd',
    'EuroNews': 'ntv+19',
    'Europa Plus TV': 'europaplus',
    'Eurosport 2': 'euro-2',
    'Eurosport HD': 'eurosporhd',
    'Eurosport News': 'eurospnews',
    'Eurosport': 'ntv+13',
    'Extreme Sports': 'ntv+23',
    'Fashion One HD': 'fashionehd',
    'Fashion One': 'fash_one',
    'Fashion TV HD': 'fashion_hd',
    'Fashion TV': 'fashion_tv',
    'Fine Living Network': 'fln',
    'Food Network': 'foodnet',
    'Fox Life HD': 'foxlife_hd',
    'Fox Life': 'fox life',
    'Fox': 'fox crime',
    'France 24 (FR)': 'france_fr',
    'France 24': 'france24',
    'French Lover': 'french_lov',
    'Galaxy TV': 'galaxy_tv',
    'Ginger HD': 'gingerhd',
    'Global Star': 'globalstar',
    'Gulli': 'gulli',
    'HardLife TV': 'hardlifetv',
    'HD Life': 'hd-life',
    'HD КИНО 2': 'hdkino2',
    'HD КИНО': 'hdkino',
    'HD Медиа 3D': 'hd_media3d',
    'HD Медиа': 'hd_media',
    'HD Спорт': 'hd_sport',
    'History': 'histor ',
    'History-viasat (ENG)': 'historyeng',
    'Hustler 3DHD': 'hustle3dhd',
    'Hustler TV Europe': 'hustler',
    'iConcerts': 'iconcerts',
    'Investigation Discovery': 'investigat',
    'IQ HD': 'iqhd',
    'JimJam': 'jimjam',
    'JSTV TV': 'jstv',
    'JuCeTV': 'jucetv',
    'Luxe HD': 'luxe_tv_hd',
    'Luxe.TV': 'luxe_tv',
    'Man TV': 'man_tv',
    'MCM POP': 'mcmpop',
    'MCM TOP': 'mcmtop',
    'Mezzo Live HD': 'mezzolive',
    'Mezzo': 'ntv+26',
    'MGM HD': 'mgm_hd',
    'Motors TV': 'motors_tv',
    'MTV Dance International': 'mtvdi',
    'MTV Dance': 'mtv_dance',
    'MTV European': 'mtv_europ',
    'MTV Hits International': 'mtvhi',
    'MTV Hits': 'mtv_hits',
    'MTV Live HD': 'mtv_livehd',
    'MTV Music': 'mtv_music',
    'MTV Rocks International': 'mtvri',
    'MTV Rocks': 'mtv_rocks',
    'MTV Russia': 'mtvrus',
    'MTV.AM': 'mtv_am',
    'MusicBox RU': 'musicbox-r',
    'MusicBox TV': 'musicbox-t',
    'myZen.tv': 'myzen.tv',
    'Nat Geo WILD HD': 'natgeow_hd',
    'Nat Geo WILD': 'ntv+18',
    'National Geographic HD': 'nat_geo_hd',
    'National Geographic': 'ntv+20',
    'Nautical channel': 'nautical',
    'NewsOne': 'newsone',
    'NHK WORLD TV': 'nhk_world',
    'Nick Jr': 'nick_jr',
    'Nickelodeon HD': 'nickelodhd',
    'Nickelodeon': 'ntv+15',
    'Ocean TV': 'ocean-tv',
    'Outdoor Channel': 'outdoor',
    'Outdoor HD': 'outdoor hd',
    'Paramount Channel HD': 'paramounhd',
    'Paramount Channel': 'paramaunt',
    'Paramount Comedy Russia': 'paracomedy',
    'Playboy TV': 'playboy_tv',
    'PRO Business': 'prodengi',
    'R1': 'r1tv',
    'RAP.RU': 'rap',
    'RT Doc': 'rt_doc',
    'RT Espanol': 'rtespanol',
    'RT': 'rus_today',
    'RTG International': 'rtgint',
    'RTД HD': 'rtdrushd',
    'RTД': 'rtdrus',
    'Ru.TV': 'ru-tv',
    'Rusong TV': 'rusong_tv',
    'Russian Travel Guide': 'rtg_tv',
    'Science et Vie TV': 'encyclo',
    'SHOP24': 'style&moda',
    'Shop24extra': 'tts',
    'Shopping Live': 'shoppingli',
    'Sony Entertainment Television': 'set_russia',
    'Sony Sci-Fi': 'axnscifi',
    'Sony Turbo': 'sonyturbo',
    'Sony ТВ HD': 'set_hd',
    'STV': 'bulvar',
    'Style TV': 'style_tv',
    'TDK': 'tdk',
    'Teletravel HD': 'teletravhd',
    'TiJi': 'tiji',
    'TLC': 'tlc',
    'Top Shop TV': 'top shop t',
    'TOPSONG TV': 'topsong_t',
    'TRACE Sport Stars HD': 'trace_sphd',
    'Trace Urban': 'trace_urba',
    'Travel Channel HD': 'tr_chan_hd',
    'Travel Channel': 'trchenel',
    'Travel+Adventure HD': 'travadhd',
    'Travel+Adventure': 'travel+adv',
    'TV club': 'tvclub',
    'TV Mail': 'tv_mail',
    'TV Sale': 'tv_sale',
    'TV1000 Action': 'tv1000_act',
    'TV1000 Comedy HD': 'tv1000come',
    'TV1000 Megahit HD': 'tv1000mega',
    'TV1000 Premium HD': 'tv1000prem',
    'TV1000 Русское кино': 'tv1000_rk',
    'TV1000': 'tv1000',
    'TV21': 'tv21',
    'TV5': 'ntv+32',
    'TVMChannel': 'tvmchannel',
    'VH1 Classic': 'vh1_class',
    'VH1 European': 'vh1_euro',
    'Viasat Explore': 'explorer',
    'Viasat History': 'history',
    'Viasat Nature CEE': 'nature_cee',
    'Viasat_Sport': 'via_sport',
    'World Business Channel': 'wbc',
    'World Fashion Channel': 'w_fashion',
    'World Music Channel': 'w_music_ch',
    'XXL': 'xxl',
    'Zee TV': 'zee-tv',
    'Zoo TV': 'zootv',
    'Zooпарк': 'zoopark',
    'Авто Плюс': 'autoplus',
    'Агро ТВ': 'agro-tv',
    'БАЛАНС ТВ': 'balanstv',
    'Беларусь 24': 'belarus-tv',
    'Бобер': 'bober',
    'Боец': 'boets',
    'Бойцовский клуб': 'boits_club',
    'Бокс ТВ': 'boxingtv',
    'ВКТ': 'vkt',
    'Война и Мир': 'vim',
    'Вопросы и ответы': 'vopr-otvet',
    'Время': 'vremya',
    'Детский мир': 'ntv+8',
    'Детский': 'detskiy',
    'Дождь HD': 'rain_hd',
    'Дождь': 'rain',
    'Дом Кино Премиум': 'domkinop',
    'Дом кино': 'domkino',
    'Домашние животные': 'd_jivotnie',
    'Домашний Магазин': 'dommagazin',
    'Домашний': 'domashniy',
    'Драйв': 'drive_mtu',
    'ЕГЭ': 'ege',
    'ЕДА HD': 'eda_hd',
    'ЕДА': 'eda',
    'Еврокино': 'eurokino',
    'ЖИВИ!': 'jivi',
    'Живая планета': 'givplaneta',
    'Живая природа': 'jivpriroda',
    'Загородная жизнь': 'zagorod_zh',
    'Загородный': 'zagorodny',
    'Звезда': 'zvezda',
    'Здоровое ТВ': 'zdorov_mtu',
    'ИНВА МЕДИА ТВ': 'inva_media',
    'Иллюзион +': 'illusion+',
    'Индия ТВ': 'india',
    'Искушение': 'iskushenie',
    'История': 'istoria',
    'КРАСНАЯ ЛИНИЯ': 'kraslin',
    'КХЛ': 'ntv+9',
    'КХЛ HD': 'khl_hd',
    'Канал Disney': 'disney',
    'Карусель': 'karusel',
    'Кино ТВ': 'kinotv',
    'КиноПремиумHD': 'kinoprhd',
    'Киноклуб': 'ntv+4',
    'Кинопоказ HD-1': 'kinop_hd-1',
    'Кинопоказ HD-2': 'kinop_hd-2',
    'Кинопоказ': 'kinipokaz',
    'Киносоюз': 'ntv+6',
    'Кинохит': 'ntv+40',
    'Комеди ТВ': 'comedytv',
    'Комедия ТВ': 'komedia',
    'Коммерсант ТВ': 'kommers_tv',
    'Кто есть кто': 'who_is_who',
    'Россия К': 'kul',
    'Кухня ТВ': 'kuhna',
    'ЛДПР.ТВ': 'ldpr',
    'Лидер ТВ': 'lidertv',
    'Ля-минор': 'la-minor',
    'МИР 24': 'mir24',
    'МИР': 'mir',
    'МНОГО ТВ': 'mnogotv',
    'МУЗ ТВ': 'muz_tvnew',
    'МУЛЬТ': 'mult',
    'Мама': 'mother&chi',
    'Мир HD': 'mirhd',
    'Мир Увлечений': 'miruvlech',
    'Мир сериала': 'mir_serial',
    'Москва-24': 'moscow-24',
    'Москва Доверие': 'doverie',
    'Моя Планета': 'my_planet',
    'Мужское кино': 'menkino',
    'Мужской': 'muzhskoj',
    'Музыка Первого': 'muz-one',
    'Мультимания': 'multimania',
    'НТВ': 'ntv',
    'НТВ-ПЛЮС Баскетбол': 'ntv+42',
    'НТВ-ПЛЮС КИНО ПЛЮС': 'ntv+34',
    'НТВ-ПЛЮС НАШЕ КИНО': 'ntv+3',
    'НТВ-ПЛЮС Наш футбол': 'ntv+1',
    'НТВ-ПЛЮС СПОРТ ПЛЮС': 'ntv+2',
    'НТВ-ПЛЮС СПОРТ': 'ntv+5',
    'НТВ-ПЛЮС Теннис': 'ntv+43',
    'НТВ-ПЛЮС Футбол 1': 'ntv+11',
    'НТВ-ПЛЮС Футбол 2': 'ntv+44',
    'НТВ-Плюс 3D': 'ntv+3d',
    'Надежда': 'nadegda',
    'Нано ТВ': 'nano_tv',
    'Настоящее Страшное Телевидение': 'nstv',
    'Наука 2.0': 'nauka_2.0',
    'Наше Новое Кино': 'ntv+7',
    'НашеHD': 'nachehd',
    'Недвижимость': 'nedvigim',
    'Ностальгия': 'nostalgi',
    'Ночной клуб': 'nightclub',
    'О2ТВ': 'o2tv',
    'Общественное телевидение России': 'otr',
    'Оружие': 'weapons',
    'Остросюжетное HD': 'ostrohd',
    'Охота и рыбалка': 'ha&fi_mtu',
    'Охотник и Рыболов HD': 'ohotrybhd',
    'Охотник и Рыболов': 'ohot&ribal',
    'ПЕРЕЦ': 'dtv',
    'ПИКТВ': '1internetk',
    'Парк развлечений': 'park_razvl',
    'Первый HD': '1tvhd',
    'Первый метео': '1_meteo',
    'Первый образовательный': '1obrazovat',
    'Первый': '1tv',
    'Премьера': 'ntv+10',
    'Продвижение': 'prodvigeni',
    'Просвещение': 'prosvejeni',
    'Психология 21': 'psihology',
    'Пятница': 'friday',
    'РБК': 'rbk',
    'РЕН ТВ': 'rentv',
    'РЖД': 'rgd',
    'РТВ - Любимое кино': 'rtvi-lk',
    'РТВ - Наше кино': 'rtvi-nk',
    'Радость Моя': 'radost_moj',
    'РазТВ': 'raz-tv',
    'Ретро': 'retro_mtu',
    'Россия 1': 'rtr',
    'Россия 2': 'sport',
    'Россия 24': 'vesti',
    'Россия HD': 'rtrhd',
    'Русская ночь': 'rusnight',
    'Русский Детектив': 'rudetektiv',
    'Русский Иллюзион': 'ru_illusio',
    'Русский Экстрим': 'ru_extrem',
    'Русский бестселлер': 'rus-bestst',
    'Русский роман': 'rusroman',
    'Рыжий': 'rigiy',
    'СТС Love': 'stslove',
    'СТС': 'sts',
    'Сарафан': 'sarafan-tv',
    'Семейное HD': 'semeynoehd',
    'Семья': 'family',
    'Совершенно секретно': 'top_secret',
    'Союз': 'sojuz',
    'Спас ТВ': 'spas',
    'Спорт 1 HD': 'sport-1_hd',
    'Спорт 1': 'sport-1',
    'Спорт': 'sport_2',
    'Страна': 'strana',
    'Страшное HD': 'strahnoehd',
    'ТБН': 'tbn',
    'ТВ Центр': 'tvc',
    'ТВ-3': 'tv3',
    'ТНВ': 'tnv',
    'ТНВ-планета': 'tnv_pl',
    'ТНТ': 'tnt',
    'ТРО': 'tro',
    'Твой': 'tvoy',
    'Театр': 'teatr',
    'Теледом': 'teledom',
    'Телеканал «360°»': '360d',
    'Телекафе': 'telekafe',
    'Телеклуб': 'ntv+39',
    'Телепутешествия': 'teletravel',
    'Техно 24': 'tehno24',
    'Тонус ТВ': 'tonus-tv',
    'Точка ТВ': 'toshkatv',
    'Три Ангела': '3angela',
    'ТурИнфо': 'turinfo',
    'Улыбка Ребенка': 'ulibkarebe',
    'Усадьба': 'usadba_mtu',
    'Успех': 'uspeh',
    'Феникс+ Кино': 'feniks',
    'Футбол': 'footballtv',
    'ЧП.Info': '4p.info',
    'Шансон-TB': 'shanson',
    'Эгоист ТВ': 'egoist-tv',
    'Ю': 'u',
    'Ювелирочка': 'uvelir',
    'Юмор BOX': 'humour-tv',
}

import re
known = []
unknown = []
with open('our_channels.txt') as inp:
    channels = {k.decode('utf8').lower(): v for k, v in channels.iteritems()}
    for line in inp:
        line = line.decode('utf8').strip()
        if len(line) < 1 or re.match('^=', line):
            continue
        if line.lower() in channels:
            known.append((line, channels[line.lower()]))
        else:
            unknown.append(line)

#print '===== Known'
for i in sorted(known, key=(lambda t: t[0])):
    #print u'\t{} -> {}'.format(*i)
    print u'INSERT INTO Channels(name, button, link) values ("{}", 0, "{}");'.format(*i).encode('utf8')

#print '===== Unknown:', len(unknown)
#for i in unknown:
#    print u'\t{}'.format(i)

